### ISSUE TITLE
Composer.lock shouldn't be committed for components

### ISSUE THREAD

**Issue by elliotwms** [itsoneiota/event-publisher-php#1]
https://philsturgeon.uk/php/2014/11/04/composer-its-almost-always-about-the-lock-file/

It could create some package dependency conflicts between the package and the application using it. You're using specific versions of the dependencies so the problem may crop up there as well just as a heads up

composer.phar probably shouldn't be in there either, instead consider [installing Composer globally](https://getcomposer.org/doc/00-intro.md#globally)

**Comment by owenmorgan** [comment]
sorted.
